### ISSUE TITLE
SubqueryAggregate fails with " more than one row returned by a subquery used as an expression" for some(?) models that have default ordering

### ISSUE THREAD

**Issue by tfh-galbraith** [martsberger/django-sql-utils#3]
While trying to tidy up some queries in an existing 1.11 project, came across an interesting bug and hopefully tracked it a little way down.

When trying to use postgres' `ARRAY_AGG` to collect some m2m names together as described in the readme, for certain queries it would give a 
`django.db.utils.ProgrammingError: more than one row returned by a subquery used as an expression`

It seems that it's related to those models having a
```
class Meta:
    ordering = ('name',)
```
(where name is the field I want to aggregate)

https://github.com/tfh-galbraith/django-sql-utils/commit/16827213aa3ef43e630f0fd79de5cc6a4d44366c

is a quick test based on yours which just sets that property on the Authors model to demonstrate.

Not sure I fully understand all the magic going on, but the issue seems to be that it adds the final target to the aggregation group by, when it potentially shouldn't?

Explicitly setting the `unordered` property/attr seems to fix this test, but I'm not sure if that is sufficient or if its just masking the problem except in the simple tests I've tried.

**Comment by martsberger** [comment]
Setting `unordered = True` is a good workaround if you don't need your array ordered. But this highlights that what is unsupported is adding an explicit ordering the way ArrayAgg  (and StringAgg) do.

**Comment by martsberger** [comment]
I can't reproduce the `more than one row returned by a subquery` error in the original description. Ordering has been added since this issue was opened.
