### ISSUE TITLE
Broken in Django 3.0

### ISSUE THREAD

**Issue by hannseman** [martsberger/django-sql-utils#4]
This commit appears to have broken it: https://github.com/django/django/commit/96b6ad94d9ebbd57b77b44e185ee215b5b899ac8

Passing `None` as the `queryset` parameter now crashes with `AttributeError: 'NoneType' object has no attribute 'query'` at https://github.com/martsberger/django-sql-utils/blob/master/sql_util/aggregates.py#L22

**Comment by martsberger** [comment]
Yes, the internals of Subquery have changed to use queryset.query instead of queryset. So, this needs to be updated in django-sql-utils. Not sure whether there should be one version that works with both Django 2.x and 3.0, I'll see how bad that makes the code.
