### ISSUE TITLE
Django 3.0 released

### ISSUE THREAD

**Issue by lundberg** [martsberger/django-sql-utils#7]
Now that Django 3.0 is released, a version bump and pypi release would be great.

Thanks

**Comment by lundberg** [comment]
Btw, current version on pypi (`0.4.2`) lacks github tag/release.

**Comment by martsberger** [comment]
Thanks for the reminder, new release coming soon.

**Comment by martsberger** [comment]
Version 0.5.0 is compatible with Django 3.0
https://pypi.org/project/django-sql-utils/0.5.0/

**Comment by lundberg** [comment]
Sweet, thanks!
