### ISSUE TITLE
Aggregates on child fields doesn't work on update

### ISSUE THREAD

**Issue by novadev94** [martsberger/django-sql-utils#8]
Subqueries only work on `annotate` but not `update`. For example
```python
Blog.objects.update(rating=SubqueryAvg('entries__rating'))
```
raises a `FieldError: Joined field references are not permitted in this query`

However, this works without any problems
```python
Blog.objects.update(entry_count=SubqueryCount('entries'))
```

I expected `django-sql-utils` to have the same capabilities as the approach described at https://www.paulox.net/2018/10/01/updating-a-django-queryset-with-annotation-and-subquery/, but it doesn't.

**Comment by martsberger** [comment]
Fixed this issue in this commit https://github.com/martsberger/django-sql-utils/commit/eae2d94c5b56f2cc13f244ed53a3a96e0911f37d
